name: Deploy para o Servidor CTI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Sincronizar pasta src via rsync/SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "projetoscti.com.br"
          REMOTE_USER: "ra2457040"
          REMOTE_PORT: "4026"
          TARGET: "/home/ra2457040/public_html"
          SOURCE: "src/"
          ARGS: "-rltgoDzvO --delete"